export default [
  {
    id: 'GGOEAFKA087499',
    category: 'mobiles',
    price: '39960',
    name: 'iPhone 14 Pro Max',
    type: 'Type1',
    imageLink: 'Apple_iPhone_14_Pro_Max.jpg',
  },
  {
    id: 'GGOEAFKA087599',
    category: 'mobiles',
    price: '5220',
    name: 'Samsung A13 4GB Ram',
    type: 'Type1',
    imageLink: 'Samsung_A13_4GB_Ram.jpg',
  },
  {
    id: 'GGOEGEBK094499',
    category: 'mobiles',
    price: '17099',
    name: 'Redmi Note 10 Pro',
    type: 'Type1',
    imageLink: 'RedmiNote10Pro.jpg',
  },
  {
    id: 'GGOEGFKA086699',
    category: 'mobiles',
    price: '12299',
    name: 'HUAWEI Mate 20 Pro',
    type: 'Type1',
    imageLink: 'HUAWEI Mate 20 Pro.jpg',
  },
  {
    id: 'GGOEWCKQ085457',
    category: 'labtops',
    price: '16099',
    name: 'Lenovo V15-ADA',
    type: 'Type2',
    imageLink: 'Lenovo V15-ADA.jpg',
  },
  {
    id: 'GGOEGHPB071610',
    category: 'labtops',
    price: '10599',
    name: 'Lenovo IdeaPad Gaming 3',
    type: 'Type2',
    imageLink: 'Lenovo IdeaPad Gaming 3.jpg',
  },
  {
    id: 'GGOEGHPJ094299',
    category: 'labtops',
    price: '9699',
    name: 'Lenovo Laptop ideapad L340',
    type: 'Type2',
    imageLink: 'Lenovo Laptop ideapad L340.jpg',
  },
  {
    id: 'GGOEGHPJ094399',
    category: 'labtops',
    price: '19599',
    name: 'Lenovo V145-15AST',
    type: 'Type2',
    imageLink: 'Lenovo V145-15AST.jpg',
  },
  {
    id: 'GGOEWXXX0827',
    category: 'printers',
    price: '1899',
    name: 'Canon PIXMA TS3440 Wireless',
    type: 'Type3',
    imageLink: 'Canon PIXMA TS3440 Wireless.jpg',
  },
  {
    id: 'GGOEWXXX0828',
    category: 'printers',
    price: '1899',
    name: 'Premium Refill Ink 4 Color',
    type: 'Type3',
    imageLink: 'Premium Refill.jpg',
  },
  {
    id: 'GGOEGBRJ037399',
    category: 'printers',
    price: '7999',
    name: 'XPrinter XP-K200L',
    type: 'Type3',
    imageLink: 'XPrinter XP-K200L.jpg',
  },
  {
    id: 'GGOEGDHJ087399',
    category: 'printers',
    price: '1499',
    name: 'Thermal Xp-350b Barcode',
    type: 'Type3',
    imageLink: 'Thermal Xp-350b Barcode.jpg',
  },
  {
    id: 'GGOEADHB085999',
    category: 'accessories',
    price: '2399',
    name: 'GAMING HEADPHONE',
    type: 'Type3',
    imageLink: 'GAMING HEADPHONE.jpg',
  },
  {
    id: 'GGOEADHB086299',
    category: 'accessories',
    price: '999',
    name: 'HAVIT Gamenote HV2229D',
    type: 'Type4',
    imageLink: 'HAVIT Gamenote HV2229D.jpg',
  },
  {
    id: 'GGOEGDHC087099',
    category: 'accessories',
    price: '2399',
    name: '5m LED Strip lights 3528',
    type: 'Type4',
    imageLink: '5m LED Strip lights 3528.jpg',
  },
  {
    id: 'GGOEGDHH087299',
    category: 'accessories',
    price: '2399',
    name: 'Dust Plug - 13Pcs/Set Anti Dust',
    type: 'Type4',
    imageLink: 'Dust Plug.jpg',
  },
  {
    id: 'GGOEGDHQ093399',
    category: 'accessories',
    price: '2399',
    name: 'GM-3501 Gaming Stereo',
    type: 'Type4',
    imageLink: 'GM-3501 Gaming Stereo.jpg',
  },
];

export const images = [
  {
    url: 'https://m.media-amazon.com/images/I/71yzJoE7WlL._AC_SL1500_.jpg',
    name: 'Apple_iPhone_14_Pro_Max.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/71+YEfLe3IL._AC_SL1500_.jpg',
    name: 'Samsung_A13_4GB_Ram.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/61RtZ8HMIYL._AC_SL1500_.jpg',
    name: 'RedmiNote10Pro.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/61sehSlvw5L._AC_SL1500_.jpg',
    name: 'HUAWEI Mate 20 Pro.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/51i17zTidPL._AC_SL1000_.jpg',
    name: 'Lenovo IdeaPad Gaming 3.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/516F3sfYp4L._AC_SL1190_.jpg',
    name: 'Lenovo V15-ADA.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/51ZpUSrig5S._AC_SL1067_.jpg',
    name: 'Lenovo Laptop ideapad L340.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/81QGhmhCNuL._AC_SL1500_.jpg',
    name: 'Lenovo V145-15AST.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/61q203yYJsS._AC_SL1000_.jpg',
    name: 'GAMING HEADPHONE.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/71Vp8uHO97L._AC_SL1500_.jpg',
    name: 'Premium Refill.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/71eMkZPqWZL._AC_SL1499_.jpg',
    name: 'Canon PIXMA TS3440 Wireless.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/81ZmX0LQtAS._AC_SL1500_.jpg',
    name: 'XPrinter XP-K200L.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/51GsqlhQgYL._AC_SL1000_.jpg',
    name: 'Thermal Xp-350b Barcode.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/61CARXIYEZL._AC_SL1500_.jpg',
    name: '5m LED Strip lights 3528.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/51TJs0BAwwS._AC_.jpg',
    name: 'Dust Plug.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/61opgFvAkOL._AC_SL1500_.jpg',
    name: 'GM-3501 Gaming Stereo.jpg',
  },
  {
    url: 'https://m.media-amazon.com/images/I/71qhevnVShS._AC_SL1500_.jpg',
    name: 'HAVIT Gamenote HV2229D.jpg',
  },
];
